apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka-deployment
spec:
  selector:
    matchLabels:
      app: eureka-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-deployment
    spec:
      containers:
        - name: eureka
          image: jeanlucasofm/eureka-service
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://10.97.158.229:8081"