apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-deployment
    spec:
      containers:
        - name: gateway
          image: jeanlucasofm/gateway-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-service:8081"
            - name: GATEWAY_CORS_ALLOWED_ORIGIN
              value: "http://frontend-service:3000"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"