apiVersion: apps/v1
kind: Deployment
metadata:
  name: pago-deployment
  labels:
    app: pago-deployment
spec:
  selector:
    matchLabels:
      app: pago-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: pago-deployment
    spec:
      containers:
        - name: pago
          image: jeanlucasofm/pago-service
          ports:
            - containerPort: 8085