apiVersion: apps/v1
kind: Deployment
metadata:
  name: pago-deployment
  labels:
    app: pago-deployment
spec:
  selector:
    matchLabels:
      app: pago-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: pago-deployment
    spec:
      containers:
        - name: pago
          image: jeanlucasofm/pago-service
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-service:8081"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/tingeso2"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"