apiVersion: apps/v1
kind: Deployment
metadata:
  name: porcentaje-deployment
  labels:
    app: porcentaje-deployment
spec:
  selector:
    matchLabels:
      app: porcentaje-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: porcentaje-deployment
    spec:
      containers:
        - name: porcentaje
          image: jeanlucasofm/porcentaje-service
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-service:8081"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/tingeso2"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"