apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-service
spec:
  selector:
    app: postgres-deployment
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432